---
- name: install liquidsoap
  apt: name=liquidsoap state=present
- name: config directory
  file: path=/etc/liquidsoap state=directory
- name: configuration file
  template: src=radio.liq.j2 dest=/etc/liquidsoap/radio.liq
  notify: restart
- name: writable recording directory
  file: path=/music/recs state=directory mode=777
- name: check recording directory is writable - if this fails then the host system may need to adjust the permissions on the recs folder
  shell: ls -dl /music/recs/ | grep -qe '^drwxrwxrwx'
  changed_when: 0
