---

- name: install liquidsoap
  apt:
    name={{ item }}
    state=present
    default_release=testing
  with_items:
      - liquidsoap
      - liquidsoap-plugin-mad
      - liquidsoap-plugin-lame
      - liquidsoap-plugin-vorbis
      #- liquidsoap-plugin-flac
      - liquidsoap-plugin-icecast
      #- multiarch-support
      - festival

- name: config directory exists
  file:
    path=/etc/liquidsoap
    state=directory

- name: copy configuration file
  template:
    src=radio.liq.j2
    dest=/etc/liquidsoap/radio.liq
  notify:
    restart liquidsoap

- name: writable recording directory
  file: path=/music/recs state=directory mode=777

- name: check recording directory is writable - if this fails then the host system may need to adjust the permissions on the recs folder
  shell: ls -dl /music/recs/ | grep -qe '^drwxrwxrwx'
  changed_when: 0

- name: check liquidsoap is running
  service:
    name=liquidsoap
    state=started
    enabled=yes
    pattern="/usr/bin/liquidsoap -d /etc/liquidsoap/radio.liq"
  notify: restart
