---
# This will install an irc daemon with basic user
# possibly also install a screen into an irssi
# admin session 
- name: install liquidsoap package 
  pkgng: name={{ item }} state=present
  with_items:
   - liquidsoap    # stream mangler
   - festival      # Speech synth 
   - festvox-kal16 # vocab for synth
   - sox           # audio convert
  notify: restart liquidsoap 

- name: configure
  template: src=template.liq dest=/usr/local/etc/liquidsoap/radio.liq mode=644 owner="liquidsoap" group="liquidsoap"
  notify: restart liquidsoap 

- name: speech synth
  copy: src=text2wave dest=/usr/local/bin/text2wave mode=755 owner="root" group="bin"

- name: enable service
  lineinfile: dest=/etc/rc.conf regexp="^liquidsoap_enable=" line="liquidsoap_enable=\"YES\""
  notify: restart liquidsoap
