---

- name: common system elements
  hosts: all
  sudo: true
  roles:
    - 'system'

- name: radio
  hosts: radio
  sudo: true
  roles:
    - 'ANXS.postgresql'
    - 'icecast'
    - 'liquidsoap'
    - 'supybot'

- name: web server
  hosts: nginx
  sudo: true
  roles:
    - 'jdauphant.nginx'
    - 'nat-ufw'