---

- name: common system elements
  hosts: all
  sudo: true
  roles:
    - 'system'
    - 'ANXS.postgresql'
    - 'jdauphant.nginx'
    - 'liquidsoap'
    - 'icecast'
    #- 'nat-ufw'
#    - 'supybot'
