---
# This will install an irc daemon with basic user
# possibly also install a screen into an irssi
# admin session 
- name: Install internet relay chat daemon 
  pkgng: name={{ item }} state=present
  with_items:
   - inspircd 
  notify: restart inspircd 

- name: configure internet relay chat daemon 
  copy: src=inspircd.conf dest=/usr/local/etc/inspircd/inspircd.conf
  notify: restart inspircd 

- name: enable service
  lineinfile: dest=/etc/rc.conf regexp="^inspircd_enable=" line="inspircd_enable=\"YES\""
  notify: restart inspircd

- name: run service
  service: name=inspircd state=running

- name: screen
  template: src=screen dest=/usr/local/share/screen/supybot

- name: install irc client
  pkgng: name={{ item }} state=present
  with_items:
   - irssi

- name: irc client config directory
  file: name=/home/{{ item }}/.irssi state=directory owner={{ item }} group=nobody mode=700
  with_items: admin_users

- name: configure irc client
  template: src=irssi.config dest=/home/{{ item }}/.irssi/config
  with_items: admin_users
