---
# TODO: Does this lock up the first time?
- name: enable service
  lineinfile: dest=/etc/rc.conf regexp="^firewall_enable=" line="firewall_enable=\"YES\""
#  notify: restart service 

- name: enable logging
  lineinfile: dest=/etc/rc.conf regexp="^firewall_logging=" line="firewall_logging=\"YES\""
#  notify: restart service 

- name: configure script 
  lineinfile: dest=/etc/rc.conf regexp="^firewall_script=" line="firewall_script=\"/etc/ipfw.rules\""
#  notify: restart service

- name: install script
  copy: src=ipfw.rules dest=/etc/ipfw.rules mode=700 owner=root group=wheel

- name: ruleset directory
  file: dest=/etc/ipfw.rules.d mode=770 owner=root group=wheel state=directory

- name: 000xx loopback ruleset
  copy: src=loopback.rules dest=/etc/ipfw.rules.d/loopback.rules mode=700 owner=root group=wheel

- name: 002xx trusted ruleset
  template: src=trusted.rules dest=/etc/ipfw.rules.d/trusted.rules mode=700 owner=root group=wheel

- name: 004xx bogon ruleset
  copy: src=bogon.rules dest=/etc/ipfw.rules.d/bogon.rules mode=700 owner=root group=wheel

- name: 006xx mandatory ruleset
  copy: src=mandatory.rules dest=/etc/ipfw.rules.d/mandatory.rules mode=700 owner=root group=wheel

- name: 008xx host ruleset
  template: src=host.rules dest=/etc/ipfw.rules.d/host.rules mode=700 owner=root group=wheel

- name: 65xxx default ruleset
  copy: src=default.rules dest=/etc/ipfw.rules.d/default.rules mode=700 owner=root group=wheel

# TODO: Does this lock up the first time?
#- name: start service
#  service: name=ipfw state=started
