---
- name: install the linux compatibility package 
  pkgng: name={{ item }} state=present
  with_items:
  - linux_base-f10

- name: enable linux compatability 
  lineinfile: dest=/etc/rc.conf regexp="^linux_enable=" line="linux_enable=\"YES\""

- shell: kldstat
  register: kldstat
  changed_when: false

- shell: kldload linux
  when: kldstat.stdout.find('linux') == -1

# Check to see if taglib has been installed in the linux environment
# never fails, only used as a register to see if other tasks are needed
- shell: test -f /compat/linux/usr/lib/libtag.so.1 
  register: taglib 
  failed_when: false
  changed_when: "taglib.rc != 0"

# cpio only takes STDIN and ansible cannot do io redirection
# so upload a shell script and run that
- copy: src=install-fc10-taglib.sh dest=/tmp/install-fc10-taglib.sh
  when: "taglib.rc != 0"

- name: install taglib
  command: chdir=/compat/linux sh /tmp/install-fc10-taglib.sh 
  when: "taglib.rc != 0"

# Check to see if echonest fingerprinting is installed
# never fails, only used as a register to see if other tasks are needed
- shell: test -f /compat/linux/opt/ENMFP_codegen/codegen.Linux-i686 
  register: codegentest 
  failed_when: false
  changed_when: "codegentest.rc != 0"

- name: get ENMFP codegen binary blob
  command: chdir=/tmp curl -O http://static.echonest.com/ENMFP_codegen.zip
  when: "codegentest.rc != 0"

- name: EMNFP directory needs to be world readable
  file: state=directory mode=0555 owner=root group=wheel path=/compat/linux/opt/ENMFP_codegen

- name: extract codegen into opt directory of linux env
  command: unzip -u /tmp/ENMFP_codegen.zip '*i686*' -d /compat/linux/opt
  when: "codegentest.rc != 0"

- name: install symlink
  file: state=link mode=0555 owner=root group=wheel src=/compat/linux/opt/ENMFP_codegen/codegen.Linux-i686 dest=/usr/local/bin/codegen
