---

- name: Testing repository - main, contrib and non-free branches
  apt_repository:
    repo='deb http://http.us.debian.org/debian testing main non-free contrib'
    state=present

- name: Testing security updates repository
  apt_repository:
    repo='deb http://security.debian.org/ testing/updates main contrib non-free'
    state=present

- name: Create radio role account
  group:
    name={{ radio_group }}
    state=present

- include: vagrant.yml
  when:
    "'vagrant' in group_names"