---
- name: install package
  yum: name=docker-io state=installed
- name: configure docker daemon 
  template: src=sysconfig.j2 dest=/etc/sysconfig/docker
  notify: restart docker daemon
- name: install python docker client
  yum: name=python-docker-py state=installed
