- name: Install Icecast2 server
  apt: name=icecast2 state=present
- name: config directory
  file: path=/etc/icecast2 state=directory
- name: icecast configuration file
  template: src=icecast.xml.j2 dest=/etc/icecast2/icecast.xml
  notify: restart
- name: /etc/defaults/icecast2
  template: src=etc_default_icecast2.xml.j2 dest=/etc/default/icecast2
  notify: restart
- name: check icecast is running
  service:
    name=icecast2
    state=started
    enabled=yes
    pattern="/usr/bin/icecast2 -b -c /etc/icecast2/icecast.xml"
